name: Release node tsconfig

on: workflow_dispatch

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: aspithost/actions/.github/workflows/release.yml
    permissions:
      contents: write
    with:
      package-path: packages/node
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
